### ISSUE TITLE
Incompatible with Corpse Complex "Recoverable XP"

### ISSUE THREAD

**Issue by CalaMariGold** [CaliforniaDemise/Fixeroo#2]
Recoverable XP with Fixeroo will always be a tiny amount with Corpse Complex experience module enabled. Even if recoverable XP is 100%, the actual amount of XP on the ground when the player dies is a tiny fraction of what it should be.

**Comment by CaliforniaDemise** [comment]
Corpse Complex experience module does some weird shit that has nothing to do with XP Orbs. It looks like an issue on Corpse Complex's side

**Comment by CaliforniaDemise** [comment]
I'm quite certain that this issue doesn't occur because of Fixeroo.
- I tested with and without Fixeroo and it always gave the same amounts of XP. (It definitely gives less than it should but it has nothing to do but results aren't different)
- Fixeroo doesn't change the amount of XP you get from XP orbs.
- And if you were using the latest version back then, that version didn't worked :trollface: 

Fell free to re-open the issue if there's actually one.
